DROP TABLE IF EXISTS location CASCADES;
DROP TABLE IF EXISTS weather CASCADES;

CREATE TABLE location (
  id SERIAL PRIMARY KEY NOT NULL,
  city TEXT NOT NULL
);

CREATE TABLE weather (
  id SERIAL PRIMARY KEY NOT NULL
);